export const DARK_THEME = {
  STATUS_BAR_STYLE: "light",
  SPACINGS: {
    GAP: 20,
    PADDING: 20,
  },
  COLORS: {
    PRIMARY: "#121212",
    PRIMARY_BACKGROUND: "rgb(119, 119, 119)",
    SECONDARY: "#1e1e1e",
    TERTIARY: "red",
    DISABLED_BUTTON: "#F0EFEF",
    DISABLED_ICON: "#E4E4E4",
    TEXT: "white",
    TEXT_LIGHT: "white",
    TEXT_DARK: "#121212",
    HEADER: "#121212",
    HEADER_TEXT: "white",
    TAB_BAR: "#121212",
    TAB_BAR_TEXT: "white",
    CHECKBOX: "white",
    CHECKBOX_ICON: "#121212",
    LABEL: "#989898",
    INPUT: "white",
    INPUT_ERROR: "red",
    STATUS_BAR: "#121212",
    STATUS_BAR_TEXT: "white",
    NAVIGATION_BAR: "#121212",
    ITERATION_COUNT: "#121212",
    ITERATION_COUNT_TEXT: "white",
    CURRENT_ITERATION_BLOCK: "#1e1e1e",
  },
} as const

export const LIGHT_THEME = {
  STATUS_BAR_STYLE: "dark",
  SPACINGS: {
    GAP: 20,
    PADDING: 20,
  },
  COLORS: {
    PRIMARY: "white",
    PRIMARY_BACKGROUND: "rgba(148, 148, 148, 0.13)",
    SECONDARY: "#121212",
    TERTIARY: "red",
    DISABLED_BUTTON: "#F0EFEF",
    DISABLED_ICON: "#E4E4E4",
    TEXT: "#121212",
    TEXT_LIGHT: "white",
    TEXT_DARK: "#121212",
    HEADER: "white",
    HEADER_TEXT: "#121212",
    TAB_BAR: "white",
    TAB_BAR_TEXT: "#121212",
    CHECKBOX: "#121212",
    CHECKBOX_ICON: "white",
    LABEL: "#121212",
    INPUT: "white",
    INPUT_ERROR: "red",
    STATUS_BAR: "white",
    STATUS_BAR_TEXT: "#121212",
    NAVIGATION_BAR: "white",
    ITERATION_COUNT: "white",
    ITERATION_COUNT_TEXT: "#121212",
    CURRENT_ITERATION_BLOCK: "white",
  },
} as const